title: Anagha P
logo: /IMG_20240401_154428-removebg-preview (1).png
description: A highly motivated Data Science and AnalyƟcs student with a good foundation in programming and data science.
#show_downloads: true
theme: jekyll-theme-minimal
