title: Anagha P
logo: IMG_20240401_154428-removebg-preview (1).png
description: A highly motivated Data Science and AnalyƟcs student with a good foundation in programming and data visualization. Eager to learn advanced techniques in machine learning and big data. Passionate about using data to solve real-world problems and contribute to the evolving field of data science.
#show_downloads: true
theme: jekyll-theme-minimal
